config/routes.rb
Artest::Application.routes.draw do

resources :authors do 
  resources :books
end

resources :books, shallow:true do
  resources :chapters
  resources :pictures
end

resources :magazines do 
  resources :pictures
end

resources :chapters, shallow:true do
  resources :paragraphs
end

root :to => "mainpage#home"

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
  has_many :chapters
  has_many :paragraphs, :through => :chapters
  has_many :pictures, :as => :imageable
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :book
  has_many :paragraphs
end

app/models/magazine.rb
class Magazine < ActiveRecord::Base
  has_many :pictures, :as => :imageable
end

app/models/paragraph.rb
class Paragraph < ActiveRecord::Base
  belongs_to :chapter
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :imageable, :polymorphic => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
    @sql = Author.all.to_sql
  end

  def show
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(user_params)
    if @author.save
      redirect_to action: 'index'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def user_params
    params.require(:author).permit(:name)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @author = Author.find(params[:author_id])
    @book = @author.books.new(book_params)
    if @book.save
      redirect_to :controller => 'authors', :action => 'index'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def book_params
    params.require(:book).permit(:title)
  end

  def author_params
    params.require(:author).permit(:author_id)
  end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  def index
    @book = params[:book]
    @chapters = @book.chapter
  end

  def show
    puts params, 'peraprepeparams'
    @chapter = Chapter.find(params[:id])
  end

  def new
    @chapter = Chapter.new
  end

  def create
    @book = Book.find(params[:book_id])
    @chapter = @book.chapters.new(chapter_params)
    if @chapter.save
      redirect_to @book
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def chapter_params
    params.require(:chapter).permit(:name)
  end

end

app/controllers/magazines_controller.rb
class MagazinesController < ApplicationController

  def index
    @magazines = Magazine.all
  end
  
  def show
    @magazine = Magazine.find(params[:id])
  end

  def new
    @magazine = Magazine.new
  end

  def create
    @magazine = Magazine.new(magazine_params)
    if @magazine.save
      redirect_to action: 'index'
    else
      render 'new'
    end
  end

  private

  def magazine_params
    params.require(:magazine).permit(:name)
  end

end

app/controllers/mainpage_controller.rb
class MainpageController < ApplicationController
  def home
  end

end

app/controllers/paragraphs_controller.rb
class ParagraphsController < ApplicationController
  def index
  end

  def show
  end

  def new
    @paragraph = Paragraph.new
  end

  def create
    @chapter = Chapter.find(params[:chapter_id])
    @chapter.paragraphs.new(paragraph_params)
    if @chapter.save
      redirect_to @chapter
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def paragraph_params
    params.require(:paragraph).permit(:number)
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
  end

  def show
  end

  def new
    @context = context
    @picture = @context.pictures.new
  end

  def create
    @context = context
    @picture = context.pictures.new(picture_params)
    if @picture.save
      redirect_to @context
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  private

  def picture_params
    params.require(:picture).permit(:name)
  end

  def context
    if params[:book_id]
      Book.find(params[:book_id])
    else
      Magazine.find(params[:magazine_id])
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/_header.html.erb
<div>
  <ol>
    <li><%= link_to 'Authors', authors_path %></li>
    <li><%= link_to 'New Author', new_author_path %></li>
  </ol>
</div>

app/views/authors/index.html.erb
<%= render 'authors/header' %>
<div> authors page! </div>
<% @authors.each do |a| %>
  <ol>
    <li><%= a.name %> <%= link_to 'New Book', new_author_book_path(a) %></li>
    <li><% a.books.each do |b| %>
    <%= link_to b.title, author_book_path(a, b)%>
    <% end %>
    </li>
  </ol>
<% end %>
<%= @sql %>

app/views/authors/new.html.erb
<div>
  <%= form_for(@author) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.submit 'Save Author' %>
  <% end %>
</div>

app/views/books/new.html.erb
<div>
  <%= form_for([@author, @book], :url => author_books_path) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.submit 'Save Book' %>
  <% end %>
</div>

app/views/books/show.html.erb
<div>this is the book
  <%= link_to @book.title, @book %>
  <% if @book.pictures.any? %>
    <div>
      <%= @book.pictures.explain %>
    </div>
    <div> Pictures in this book - </div>
    <% @book.pictures.each do |picture| %>
      <li><%= picture.name %></li>
    <% end %>
  <% end %>

  <%= link_to 'New Picture', new_book_picture_path(@book) %>
  </br>

  <% if @book.chapters.any? %>
    this book has the following chapters
    <li><%= @book.chapters.to_sql %></li>
    <div>
      <ul>
        <% @book.chapters.each do |chapter| %>
          <li><%= link_to chapter.name, chapter %></li>
        <% end %>
      </ul>
  <% end %>
  <%= link_to 'New Chapter', new_book_chapter_path(@book) %>
  
  </br>
  <% if @book.paragraphs.any? %>
    this book has the following paragraphs as well
      <ul>
        <%= @book.paragraphs.explain %>
        <% @book.paragraphs.each do |paragraphs| %>
          <li><%= paragraphs.number %></li>
        <% end %>
      </ul>
  <% end %>


</div>

app/views/chapters/index.html.erb
<div>these are the chapters for </div>

app/views/chapters/new.html.erb
<div>
  <%= form_for(@chapter, :url =>book_chapters_path) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.submit 'Save Chapter' %>
  <% end %>
</div>

app/views/chapters/show.html.erb
<div>
  paragraphs in chapter
  <%= link_to @chapter.name, @chapter %>
  <% if @chapter.paragraphs.any? %>
    <div>
      <ul>
        <% @chapter.paragraphs.each do |paragraph| %>
          <li><%= link_to paragraph.number, paragraph %></li>
        <% end %>
      </ul>
  <% end %>
  
  </br>
  <%= link_to 'New Paragraph', new_chapter_paragraph_path(@chapter) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Artest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/magazines/index.html.erb
<div>Magazines!</div>
<% @magazines.each do |magazine| %>
  <li><%= link_to magazine.name, magazine %></li>
<% end %>
<%= link_to 'New Magazine', new_magazine_path %>

app/views/magazines/new.html.erb
<%= form_for(@magazine) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit 'Save Magazine' %>
<% end %>

app/views/magazines/show.html.erb
<div>the magazine 
  <%= @magazine.name %>
</div>
has the pictures
<% @magazine.pictures.each do |picture| %>
  <li> <%= picture.name %></li>
<% end %>
<%= link_to 'New picture', new_magazine_picture_path(@magazine) %>

app/views/mainpage/home.html.erb
<div>hello and welcome</div>
<%= link_to 'Authors', authors_path %>
<%= link_to 'Magazines', magazines_path %>

app/views/paragraphs/new.html.erb
<div>
  <%= form_for([@chapter, @paragraph], :url => chapter_paragraphs_path) do |f| %>
    <%= f.label :number %>
    <%= f.text_field :number %>
    <%= f.submit 'Save paragraph' %>
  <% end %>
</div>

app/views/pictures/new.html.erb
<div>new picture</div>
<%= form_for([@context, @picture],
             :url => polymorphic_path([@context, @picture])) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit 'Save Picture' %>
<% end %>